---

- name: "Playbook 1"
  hosts: localhost

  tasks:
    - name: "TASK 1 --- Collect facts about the host"
      ansible.builtin.setup:
        filter:
          - "ansible_date_time"
          
    - name : "TASK 2 --- Record the variable"
      set_fact:
        TD: "{{ ansible_date_time.date }}"