---

- name: "BGP Playbook"
  hosts: south
  connection: network_cli
  gather_facts: false

  tasks:
    - name: "Task 1"

      register: cisco_bgp_output

    - name: "Task 2"
      debug:
        msg: "{{ cisco_bgp_output }}"