---

- name: "Playbook for handlers"
  hosts: north
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Taks 1"
      cisco.ios.ios_config:
        src: "ntp.j2"
      notify: ntp_handler_example
      register: ntp_results

  handlers:
    - name: ntp_handler_example
      debug:
        msg: "{{ ntp_results }}"