---

- name: "Playbook to test some variable substritition"
  hosts: test_work
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Task 1"
      cisco.ios.ios_config:
        src: "bgp.j2"