---

- name: "OSPF Playbook 2"
  hosts: south
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Task 1 --- Push OSPF configuration"
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: "{{ ospf.rid }}"
              network:
                - address: 0.0.0.0
                  area: 0
                  wildcard_bits: 255.255.255.255
        state: merged
      register: ospf_output
      when: "ansible_network_os == 'cisco.ios.ios'"

    - name: "Task 2 --- Display OSPF configuration"
      debug:
        msg: "{{ ospf_output }}"
      when: "ansible_network_os == 'cisco.ios.ios'"