---

- name: MY FIRST PLAYBOOK
  hosts: north
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "OSPF CONFIG"
      cisco.ios.ios_config:
        lines:
          - router-id 11.22.33.44
        parents:
          - router ospf 99
      register: my_output

    - debug: var=my_output
