---

- name: "Play 1: Testing RESTCONF"
  hosts: north
  connection: local

  tasks:
    - name: "TASK 1 --- Pull info"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/native/interface"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: GET
        return_content: true
        headers:
          Accept: "application/yang-data+json"
        validate_certs: false
      register: result

    - name: "TASK 2 --- Print result"
      debug:
        msg: "{{ result.json }}"