---

- name: "Configure Device via RESTCONF"
  hosts: test_work
  connection: local

  tasks:
    - name: "TASK 1 --- Configure OSPF"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/native/router"
        user: "{{ ansible_user }}"
        password: "{{ansible_password }}"
        method: PUT
        headers:
          Accept:
            application/yang-data+json
            # application/yang-data.errors+json
          Content-Type: 'application/yang-data+json'
        body_format: json
        body: "{{ ospf_configure }}"
        validate_certs: false
        status_code:
          - 200
          - 204