---

- name: "Register Template Example"
  hosts: test_work
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Task 1 ----- Push Config"
      cisco.ios.ios_config:
        src: "ntp.j2"
      register: ntp_result
    
    - name: "Task 2 ----- Print config"
      debug:
        msg: "{{ntp_result}}"