---

- name: "Playbook 1 --- Cisco device"
  hosts: north
  connection: network_cli

  tasks:
    - name: "TASK 1 --- Apply the provided configuration"
      cisco.ios.ios_logging_global:
        config:
          hosts:
            - hostname: "{{ item.ip }}"
        state: merged
      loop: "{{ syslog.hosts }}"
      when: item.port is not defined
      register: task_1_output

    - name: "TASK 2 --- Apply the configured configuration incl transport"
      cisco.ios.ios_logging_global:
        config:
          hosts:
            - hostname: "{{ item.ip }}"
              transport: 
                tcp:
                  port: "{{ item.port }}"
        state: merged
      loop: "{{ syslog.hosts }}"
      when: item.ip and item.port is defined
      register: task_2_output

    - name: "TASK 3 --- Print the output"
      debug:
        msg: "{{ item.commands }}"
      loop: "{{ task_1_output.results }}"
      loop_control:
        label: none
      when: item.commands is defined

    - name: "TASK 4 --- Print out the output"
      debug:
        msg: "{{ item.commands }}"
      loop: "{{ task_2_output.results }}"
      loop_control:
        label: none
      when: item.commands is defined